use std::any::TypeId;
use std::collections::HashMap;

pub struct DI {
    pub config: TypeId,
    pub db: TypeId,
    pub meta: TypeId,
    pub meilisearch: TypeId,
    pub redis: TypeId,
    pub redisForPub: TypeId,
    pub redisForSub: TypeId,
    pub redisForTimelines: TypeId,
    pub redisForReactions: TypeId,

    //#region Repositories
    pub usersRepository: TypeId,
    pub notesRepository: TypeId,
    pub announcementsRepository: TypeId,
    pub announcementReadsRepository: TypeId,
    pub appsRepository: TypeId,
    pub avatarDecorationsRepository: TypeId,
    pub noteFavoritesRepository: TypeId,
    pub noteThreadMutingsRepository: TypeId,
    pub noteReactionsRepository: TypeId,
    pub noteUnreadsRepository: TypeId,
    pub pollsRepository: TypeId,
    pub pollVotesRepository: TypeId,
    pub userProfilesRepository: TypeId,
    pub userKeypairsRepository: TypeId,
    pub userPendingsRepository: TypeId,
    pub userSecurityKeysRepository: TypeId,
    pub userPublickeysRepository: TypeId,
    pub userListsRepository: TypeId,
    pub userListFavoritesRepository: TypeId,
    pub userListMembershipsRepository: TypeId,
    pub userNotePiningsRepository: TypeId,
    pub userIpsRepository: TypeId,
    pub usedUsernamesRepository: TypeId,
    pub followingsRepository: TypeId,
    pub followRequestsRepository: TypeId,
    pub instancesRepository: TypeId,
    pub emojisRepository: TypeId,
    pub driveFilesRepository: TypeId,
    pub driveFoldersRepository: TypeId,
    pub metasRepository: TypeId,
    pub mutingsRepository: TypeId,
    pub renoteMutingsRepository: TypeId,
    pub blockingsRepository: TypeId,
    pub swSubscriptionsRepository: TypeId,
    pub hashtagsRepository: TypeId,
    pub abuseUserReportsRepository: TypeId,
    pub abuseReportNotificationRecipientRepository: TypeId,
    pub registrationTicketsRepository: TypeId,
    pub authSessionsRepository: TypeId,
    pub accessTokensRepository: TypeId,
    pub signinsRepository: TypeId,
    pub pagesRepository: TypeId,
    pub pageLikesRepository: TypeId,
    pub galleryPostsRepository: TypeId,
    pub galleryLikesRepository: TypeId,
    pub moderationLogsRepository: TypeId,
    pub clipsRepository: TypeId,
    pub clipNotesRepository: TypeId,
    pub clipFavoritesRepository: TypeId,
    pub antennasRepository: TypeId,
    pub promoNotesRepository: TypeId,
    pub promoReadsRepository: TypeId,
    pub relaysRepository: TypeId,
    pub channelsRepository: TypeId,
    pub channelFollowingsRepository: TypeId,
    pub channelFavoritesRepository: TypeId,
    pub registryItemsRepository: TypeId,
    pub webhooksRepository: TypeId,
    pub systemWebhooksRepository: TypeId,
    pub adsRepository: TypeId,
    pub passwordResetRequestsRepository: TypeId,
    pub retentionAggregationsRepository: TypeId,
    pub rolesRepository: TypeId,
    pub roleAssignmentsRepository: TypeId,
    pub flashsRepository: TypeId,
    pub flashLikesRepository: TypeId,
    pub userMemosRepository: TypeId,
    pub bubbleGameRecordsRepository: TypeId,
    pub reversiGamesRepository: TypeId,
    //#endregion
}

impl DI {
    pub fn new() -> Self {
        DI {
            config: TypeId::of::<()>(),
            db: TypeId::of::<()>(),
            meta: TypeId::of::<()>(),
            meilisearch: TypeId::of::<()>(),
            redis: TypeId::of::<()>(),
            redisForPub: TypeId::of::<()>(),
            redisForSub: TypeId::of::<()>(),
            redisForTimelines: TypeId::of::<()>(),
            redisForReactions: TypeId::of::<()>(),

            //#region Repositories
            usersRepository: TypeId::of::<()>(),
            notesRepository: TypeId::of::<()>(),
            announcementsRepository: TypeId::of::<()>(),
            announcementReadsRepository: TypeId::of::<()>(),
            appsRepository: TypeId::of::<()>(),
            avatarDecorationsRepository: TypeId::of::<()>(),
            noteFavoritesRepository: TypeId::of::<()>(),
            noteThreadMutingsRepository: TypeId::of::<()>(),
            noteReactionsRepository: TypeId::of::<()>(),
            noteUnreadsRepository: TypeId::of::<()>(),
            pollsRepository: TypeId::of::<()>(),
            pollVotesRepository: TypeId::of::<()>(),
            userProfilesRepository: TypeId::of::<()>(),
            userKeypairsRepository: TypeId::of::<()>(),
            userPendingsRepository: TypeId::of::<()>(),
            userSecurityKeysRepository: TypeId::of::<()>(),
            userPublickeysRepository: TypeId::of::<()>(),
            userListsRepository: TypeId::of::<()>(),
            userListFavoritesRepository: TypeId::of::<()>(),
            userListMembershipsRepository: TypeId::of::<()>(),
            userNotePiningsRepository: TypeId::of::<()>(),
            userIpsRepository: TypeId::of::<()>(),
            usedUsernamesRepository: TypeId::of::<()>(),
            followingsRepository: TypeId::of::<()>(),
            followRequestsRepository: TypeId::of::<()>(),
            instancesRepository: TypeId::of::<()>(),
            emojisRepository: TypeId::of::<()>(),
            driveFilesRepository: TypeId::of::<()>(),
            driveFoldersRepository: TypeId::of::<()>(),
            metasRepository: TypeId::of::<()>(),
            mutingsRepository: TypeId::of::<()>(),
            renoteMutingsRepository: TypeId::of::<()>(),
            blockingsRepository: TypeId::of::<()>(),
            swSubscriptionsRepository: TypeId::of::<()>(),
            hashtagsRepository: TypeId::of::<()>(),
            abuseUserReportsRepository: TypeId::of::<()>(),
            abuseReportNotificationRecipientRepository: TypeId::of::<()>(),
            registrationTicketsRepository: TypeId::of::<()>(),
            authSessionsRepository: TypeId::of::<()>(),
            accessTokensRepository: TypeId::of::<()>(),
            signinsRepository: TypeId::of::<()>(),
            pagesRepository: TypeId::of::<()>(),
            pageLikesRepository: TypeId::of::<()>(),
            galleryPostsRepository: TypeId::of::<()>(),
            galleryLikesRepository: TypeId::of::<()>(),
            moderationLogsRepository: TypeId::of::<()>(),
            clipsRepository: TypeId::of::<()>(),
            clipNotesRepository: TypeId::of::<()>(),
            clipFavoritesRepository: TypeId::of::<()>(),
            antennasRepository: TypeId::of::<()>(),
            promoNotesRepository: TypeId::of::<()>(),
            promoReadsRepository: TypeId::of::<()>(),
            relaysRepository: TypeId::of::<()>(),
            channelsRepository: TypeId::of::<()>(),
            channelFollowingsRepository: TypeId::of::<()>(),
            channelFavoritesRepository: TypeId::of::<()>(),
            registryItemsRepository: TypeId::of::<()>(),
            webhooksRepository: TypeId::of::<()>(),
            systemWebhooksRepository: TypeId::of::<()>(),
            adsRepository: TypeId::of::<()>(),
            passwordResetRequestsRepository: TypeId::of::<()>(),
            retentionAggregationsRepository: TypeId::of::<()>(),
            rolesRepository: TypeId::of::<()>(),
            roleAssignmentsRepository: TypeId::of::<()>(),
            flashsRepository: TypeId::of::<()>(),
            flashLikesRepository: TypeId::of::<()>(),
            userMemosRepository: TypeId::of::<()>(),
            bubbleGameRecordsRepository: TypeId::of::<()>(),
            reversiGamesRepository: TypeId::of::<()>(),
            //#endregion
        }
    }
}
